@CulturalEvents_HostAddress = http://localhost:5150/api/artists
@id = 45f0f0c2-d2f5-48cd-a9d9-72bc4d666c3f

POST {{CulturalEvents_HostAddress}}
Content-Type: application/json

{
    "Name": "Badabó",
    "Cpf": "111",
    "Email": "badabo@gmail.com",
    "Speciality": "Yoleleleiho"
}

### list all artists
GET {{CulturalEvents_HostAddress}}

### get artist
GET {{CulturalEvents_HostAddress}}/{{id}}

### update artist
PUT {{CulturalEvents_HostAddress}}/{{id}}
Content-Type: application/json

{
    "id": "45f0f0c2-d2f5-48cd-a9d9-72bc4d666c3f",
    "Name": "Badabó",
    "Cpf": "111",
    "Email": "badabo@gmail.com",
    "Speciality": "Yoleleleihuuuu" 
}

### display details
GET {{CulturalEvents_HostAddress}}/details/{{id}}

### delete artist
DELETE {{CulturalEvents_HostAddress}}/{{id}}