@CulturalEvents_HostAddress = http://localhost:5150

PUT {{CulturalEvents_HostAddress}}/api/tickets
Content-Type: application/json

{
    "Price": 10.00,
    "Status": true
}

### GET BY ID
GET {{CulturalEvents_HostAddress}}/api/tickets/2e36dc6c-e3a4-4437-966d-64cdecf8f20f
